import groovy.json.JsonOutput

//jenkins env variables
//env.jenkins_node_custom_workspace_path = "/var/jenkins_home/WorkSpace/Terraform-extension"

pipeline {
    agent any
    
    tools {
        terraform 'terraform-2'
    }
	
	parameters {
		choice choices: ['dev', 'prod'], description: 'Describes the Environment', name: 'workspace'
	}
    
    environment {
        PATH = "${PATH}:${getTerraform()}"
    }

    stages {
		stage('Git Checkout') {
            steps { 
				echo pwd
				sh returnStatus: true, script: 'terraform workspace new ${workspace} '
				echo pwd 
                git credentialsId: '3bb8a15a-876c-4fcc-b31d-82a6e5cd6529', url: 'https://github.com/praveen-hub/AWS.git'
				echo pwd
            }
        }
        stage('TF Init') {
            steps {
				dir('s3/'){
				echo pwd
				sh returnStatus: true, script: 'terraform workspace select ${params.workspace} '
				echo pwd
                sh 'terraform init -input=false'
                echo pwd
                echo 'Terraform was initialised successfully'
				}
            }
        }
        stage('TF Format'){
            steps {
				dir('s3/'){
				//sh 'terraform workspace select ${workspace}'
				sh returnStatus: true, script: 'terraform workspace select ${params.workspace} '
				sh "terraform fmt"
				echo 'Terraform was aligned successfully'
				}
                }
            }
		stage('TF Plan') {
            steps {
				dir('s3/'){
				sh returnStatus: true, script: 'terraform workspace select ${params.workspace}'
				echo pwd
				sh 'terraform plan -input=false -out tfplan --var-file=${params.workspace}.tfvars '
				sh 'terraform show -no-color tfplan > tfplan.txt'
                echo 'Terraform plan was initialised successfully'
				}
            }
		}
		stage('TF Apply') {
            steps {
				dir('s3/'){
			    sh returnStatus: true, script: 'terraform workspace select ${params.workspace} '
                sh 'terraform apply --var-file=${params.workspace}.tfvars --auto-approve -input=false tfplan'
                echo 'Terraform Applied successfully'
				}
            }
        }
    }
	post {
        always {
            archiveArtifacts artifacts: 'tfplan.txt'
        }
    }
}

def getTerraform(){
    def tfHome = tool name: 'terraform-2', type: 'terraform'
    return tfHome
}
